package vista;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import libreriabasica.Usuario;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        //String uuid = java.util.UUID.randomUUID().toString();
        //System.out.println(uuid);
        //String result = uuid.replaceAll("-", "");
        //System.out.println(result.substring(0, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkPass = new javax.swing.JCheckBox();
        lblFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1211, 615));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLoginMouseClicked(evt);
            }
        });
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 95, 239));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Iniciar Sesión");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        txtUser.setBackground(new java.awt.Color(236, 236, 236));
        txtUser.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Nombre de Usuario");
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        panelLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 240, 40));

        btnLogin.setBackground(new java.awt.Color(93, 95, 239));
        btnLogin.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(204, 204, 204));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 250, 40));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel5.setText("Se me olvidó la contraseña");
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Crear cuenta Nueva");
        panelLogin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 280, 40));

        txtContrasena.setBackground(new java.awt.Color(236, 236, 236));
        txtContrasena.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(204, 204, 204));
        txtContrasena.setText("Contrasena");
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContrasenaMouseClicked(evt);
            }
        });
        panelLogin.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock.png"))); // NOI18N
        panelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/group.png"))); // NOI18N
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 40));

        checkPass.setBackground(new java.awt.Color(255, 255, 255));
        checkPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkPass.setText("Recordar Contraseña");
        checkPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkPassMouseClicked(evt);
            }
        });
        panelLogin.add(checkPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jPanel1.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 440, 500));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bkPrincipal.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bk1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bk2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
 
    }//GEN-LAST:event_btnLoginMousePressed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        if (txtUser.getText().equals("Nombre de Usuario")) {
            txtUser.setText("");
            txtUser.setForeground(Color.blue);
        }
        
        if(String.valueOf(txtContrasena.getPassword()).equals("")){
            txtContrasena.setText("Contrasena");
            txtContrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMouseClicked
        if (String.valueOf(txtContrasena.getPassword()).equals("Contrasena")){
            txtContrasena.setText("");
            txtContrasena.setForeground(Color.blue);
        }
        
        if(txtUser.getText().isEmpty()){
            txtUser.setText("Nombre de Usuario");
            txtUser.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtContrasenaMouseClicked

    private void panelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLoginMouseClicked
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Nombre de Usuario");
            txtUser.setForeground(Color.gray);
        }
        
        if(String.valueOf(txtContrasena.getPassword()).equals("")){
            txtContrasena.setText("Contrasena");
            txtContrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_panelLoginMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        //Verificar que el usuario haya tecleado algo
        
        Usuario objUsr = new Usuario(txtUser.getText());
        
        System.out.println(objUsr.ValidarUsuarioString());
        
        if(txtUser.getText().isEmpty() || txtUser.getText().contains("Nombre de Usuario")) {
            JOptionPane.showMessageDialog(this, "Debes escribir un nombre de usuario.","Bienvenido al sistema...", JOptionPane.ERROR_MESSAGE);
        } else {
            if(String.valueOf(txtContrasena.getPassword()).isEmpty() || String.valueOf(txtContrasena.getPassword()).equals("Contrasena")) {
                JOptionPane.showMessageDialog(this, "Debes escribir una contraseña","Upss..", JOptionPane.ERROR_MESSAGE);
            } else {
                
                if (txtUser.getText().equals("Admin") && String.valueOf(txtContrasena.getPassword()).equals("12345")) {
                    
                    //System.out.println("Entrando al sistema... ");
                    FrmPrincipal frmPrincipal = new FrmPrincipal();
                    
                    frmPrincipal.setVisible(true);
                    
                    //this.setVisible(false);
                    dispose();
                    
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrecto.","Upss..", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void checkPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkPassMouseClicked
            
        if (checkPass.isSelected()){
            guardarContrasena();
        }
    }//GEN-LAST:event_checkPassMouseClicked

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed
    
    public void guardarContrasena () {
        File f;
        f = new File("guardarPass");
        
        try{
            FileWriter w = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);
            wr.write("Esta es una linea de codigo");
            wr.append(" - y aqui continua");
            
            wr.close();
            bw.close();
        } catch (IOException e) {}; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
